# Generated by Django 4.2.27 on 2025-12-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_alter_category_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='address',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='auth0_user_id',
            field=models.CharField(db_index=True, default='legacy-user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='auth0_user_id',
            field=models.CharField(db_index=True, default='legacy-user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='auth0_user_id',
            field=models.CharField(db_index=True, default='legacy-user', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.address'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('auth0_user_id', 'product')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
