# Generated by Django 4.2.27 on 2025-12-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_address_address_type_address_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wishlist',
            name='shop_wishli_auth0_u_fdbb1e_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
